---
title: "R Notebook"
output: html_notebook
---
```{r}
avg_age <- mean(train$age, na.rm = TRUE)
conf_int <- t.test(train$age)$conf.int[1:2]
ggplot(train, aes(age)) +
  geom_density() +
  geom_vline(aes(xintercept = avg_age), color = "red") +
  geom_vline(aes(xintercept = conf_int[1]), color = "blue") + 
  geom_vline(aes(xintercept = conf_int[2]), color = "blue")
message(paste("Average Age:", avg_age ))
message(paste("95% Confidence Intervals:", conf_int[1], "|", conf_int[2]))
```

But what if I wanted to know the expected average age?

```{r}
average_ages <- numeric(100)
for (i in seq_along(average_ages)) {
  new_sample <- sample(train$age, size = nrow(train), replace = TRUE)
  avg_new_sample <- mean(new_sample, na.rm = TRUE)
  average_ages[i] <- avg_new_sample
}
d <- data.frame(average_ages)
ggplot(d, aes(x = average_ages)) +
  geom_density() + 
  geom_vline(aes(xintercept = avg_age), color = "red") +
  geom_vline(aes(xintercept = conf_int[1]), color = "blue") + 
  geom_vline(aes(xintercept = conf_int[2]), color = "blue")
```

